Articles:
    type: entity
    table: articles
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        url:
            type: string
            length: 256
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
