Logins:
    type: entity
    table: logins
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        login:
            type: string
            length: 128
            fixed: false
            nullable: false
        password:
            type: string
            length: 45
            fixed: false
            nullable: false
        salt:
            type: string
            length: 45
            fixed: false
            nullable: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    lifecycleCallbacks: {  }
