SimpleSolution\SimpleTradeBundle\Entity\Templates:
    type: entity
    table: templates
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        title:
            type: string
            length: 255
            fixed: false
            nullable: false
        filename:
            type: string
            length: 128
            fixed: false
            nullable: false
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }