Users:
    type: entity
    table: users
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 128
            fixed: false
            nullable: false
    manyToOne:
        login:
            targetEntity: Logins
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                login_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
